name: "GitLab-CE - development"
description: "I will attempt to create a docker for running GitLab on HomeAssistant"
version: "0.0.1"
slug: "hello_world"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386